import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';
import type { Pet, Vaccination, Medication, DewormingRecord, WeightLog, VetVisit, MedicationLog } from '@pawcare/shared';
import { calculateAge } from '@pawcare/shared';

export function generatePetProfilePdf(args: {
  pet: Pet;
  vaccinations: Vaccination[];
  medications: Medication[];
  deworming: DewormingRecord[];
  weightLogs: WeightLog[];
  vetVisits: VetVisit[];
  medicationLogs: MedicationLog[];
}) {
  const { pet, vaccinations, medications, deworming, weightLogs, vetVisits, medicationLogs } = args;
  const doc = new jsPDF();

  // Header band
  doc.setFillColor(255, 107, 107);
  doc.rect(0, 0, 210, 28, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('PawCare', 14, 18);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated ${format(new Date(), 'PPP')}`, 210 - 14, 18, { align: 'right' });

  let y = 38;
  doc.setTextColor(28, 28, 30);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text(pet.name, 14, y);
  y += 8;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(110, 110, 115);
  const info = [
    `${pet.species}${pet.breed ? ' • ' + pet.breed : ''}`,
    `Age: ${calculateAge(pet.date_of_birth)}`,
    pet.gender !== 'unknown' ? `Gender: ${pet.gender}` : '',
    pet.weight_kg ? `Weight: ${pet.weight_kg} kg` : '',
    pet.is_neutered ? 'Neutered/Spayed' : 'Not neutered',
  ]
    .filter(Boolean)
    .join('   |   ');
  doc.text(info, 14, y);
  y += 6;

  if (pet.bio) {
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 67);
    const wrapped = doc.splitTextToSize(pet.bio, 180);
    doc.text(wrapped, 14, y);
    y += wrapped.length * 5 + 4;
  }

  if (vetVisits.length > 0) {
    autoTable(doc, {
      startY: y,
      head: [['Vet Visits', '', '', '']],
      body: vetVisits.map((v) => [
        v.visit_date,
        v.clinic_name ?? v.vet_name ?? '—',
        v.diagnosis ?? v.reason ?? '—',
        v.cost_inr ? `Rs ${v.cost_inr}` : '—',
      ]),
      headStyles: { fillColor: [255, 107, 107] },
      styles: { fontSize: 9 },
    });
    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;
  }

  if (vaccinations.length > 0) {
    autoTable(doc, {
      startY: y,
      head: [['Vaccination', 'Type', 'Date Given', 'Next Due']],
      body: vaccinations.map((v) => [
        v.vaccine_name,
        v.vaccine_type,
        v.date_given,
        v.next_due_date ?? '—',
      ]),
      headStyles: { fillColor: [255, 107, 107] },
      styles: { fontSize: 9 },
    });
    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;
  }

  if (medications.length > 0) {
    if (y > 240) {
      doc.addPage();
      y = 20;
    }
    autoTable(doc, {
      startY: y,
      head: [['Medications', '', '', '']],
      body: medications.map((m) => [
        m.medicine_name,
        m.dosage ?? '—',
        m.frequency,
        m.is_ongoing ? 'Ongoing' : m.end_date ?? '—',
      ]),
      headStyles: { fillColor: [255, 107, 107] },
      styles: { fontSize: 9 },
    });
    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;
  }

  if (deworming.length > 0) {
    if (y > 240) {
      doc.addPage();
      y = 20;
    }
    autoTable(doc, {
      startY: y,
      head: [['Deworming', '', '']],
      body: deworming.map((d) => [
        d.product_name,
        d.date_given,
        d.next_due_date ?? '—',
      ]),
      headStyles: { fillColor: [255, 107, 107] },
      styles: { fontSize: 9 },
    });
    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;
  }

  if (weightLogs.length > 0) {
    if (y > 240) {
      doc.addPage();
      y = 20;
    }
    autoTable(doc, {
      startY: y,
      head: [['Weight Logs', '']],
      body: weightLogs.slice(0, 12).map((w) => [w.measured_at, `${w.weight_kg} kg`]),
      headStyles: { fillColor: [255, 107, 107] },
      styles: { fontSize: 9 },
    });
  }

  // Footer watermark
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(174, 174, 178);
    doc.text(
      `Generated by PawCare • ${format(new Date(), 'PPpp')}`,
      105,
      290,
      { align: 'center' }
    );
  }

  return doc;
}
